application:
  repository: JDBC
spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/passport_office
    password: postgres
    username: postgres
  flyway:
    locations: "classpath:db/migration"
    enabled: true
logging:
  level:
    ROOT: INFO
